---
title: "sensor data"
author: "Tess Noble Strohm"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # Package with dplyr, tibble, readr, and others to help clean coding
library(dataRetrieval) # Package to download data. 
library(sf) #Geospatial package to plot and explore data
library(mapview) #Simple interface to leaflet interactive maps
library(broom) #Simplifies model outputs
library(knitr) #Makes nice tables
library(kableExtra) #Makes even nicer tables
library(lubridate) #Makes working with dates easier
library(ggthemes) #Makes plots prettier
library(tidyr) #Makes multiple simultaneous models easier
library(trend) # Allows us to explore trends. 
```

# LOAD DATA
--> BOX 3 = 5x COMPOST
--> BOX 4 = 0x COMPOST
```{r Box3}
box3 <- read.csv("BII T3 (BOX 3) copy.csv")
#write.csv(box3, file = "data/box3.csv", row.names = FALSE)

box3_clean <- box3 %>%
  dplyr::select(Timestamp = X06.01663,
                Pea_5cm_WC = Port.1, 
                Pea_5cm_Temp= Port.1.1,
                Pea_30cm_WC = Port.2, 
                Pea_30cm_Temp = Port.2.1,  
                Wheat_5cm_WC = Port.3,
                Wheat_5cm_Temp = Port.3.1, 
                Wheat_30cm_WC = Port.4, 
                Wheat_30cm_Temp = Port.4.1) %>%
  .[-c(1,2),] %>%
  mutate_at(vars(Pea_5cm_WC:Wheat_30cm_Temp),as.numeric)

```

```{r Box4}
box4 <- read_csv("BII T4 (BOX 4) copy.csv")
#write.csv(box4, file = "data/box4.csv", row.names = FALSE)

box4_clean <- box4 %>%
  dplyr::select(Timestamp = 1,
                Wheat_5cm_WC = 2, 
                Wheat_5cm_Temp= 3,
                Wheat_30cm_WC = 4, 
                Wheat_30cm_Temp = 5,  
                Pea_5cm_WC = 6,
                Pea_5cm_Temp = 7, 
                Pea_30cm_WC = 10, 
                Pea_30cm_Temp = 11) %>%
  .[-c(1,2),] %>%
  mutate_at(vars(Wheat_5cm_WC:Pea_30cm_Temp),as.numeric) 

```

# TIDY DATA
```{r Box3 Tidy}
box3_long <- box3_clean %>%
  pivot_longer(
    cols = -Timestamp
  ) %>% 
  separate(name, sep = "_", into = c("Treatment", "Depth", "Value")) %>% 
  pivot_wider(names_from = Value)

box3_long$Timestamp <- lubridate::mdy_hm(box3_long$Timestamp)
str(box3_long)
```

```{r Box4 Tidy}
box4_long <- box4_clean %>%
  pivot_longer(
    cols = -Timestamp
  ) %>% 
  separate(name, sep = "_", into = c("Treatment", "Depth", "Value")) %>% 
  pivot_wider(names_from = Value)

box4_long$Timestamp <- lubridate::mdy_hm(box4_long$Timestamp)
str(box4_long)
```

# Graph it
```{r}
plot_Box3 <- ggplot(box3_long, mapping = aes(x = Timestamp, y = WC, color = Depth)) +
  facet_wrap(~Treatment, scales = 'free') +
  geom_point() +
  scale_y_discrete(breaks = seq(0, 0.5, 0.01))
plot_Box3

plot_Box4 <- ggplot(box4_long, mapping = aes(x = Timestamp, y = WC, color = Depth)) +
  facet_wrap(~Treatment, scales = 'free') +
  geom_point() +
  scale_y_discrete(breaks = seq(0, 0.5, 0.01))
plot_Box4
```

# Analysis 

## Testing the sens.slope
on Wheat WC data form 5cm
```{r}
Wheat_WC <- box3_long %>% 
  filter(Treatment == "Wheat", Depth == "5cm")

str(Wheat_WC)

WC_slope <- sens.slope(Wheat_WC$WC)
WC_slope
```

## The 'tidier' funciton 
```{r}
tidier <- function(mod = WC_slope){
  
  tidy(mod) %>%
    mutate(slope = mod$estimates) #this adds a new column "slope" which is derivered from the 'estimates' from the OG model
  
}

tidier()
```


## Nesting
Box 3:
```{r}
Box3_nest <- box3_long %>%
  # rename parameter as ion to make it more clear
  group_by(Treatment,Depth) %>%
  nest() 

head(Box3_nest)
```
Box 4: 
```{r}
Box4_nest <- box4_long %>%
  # rename parameter as ion to make it more clear
  group_by(Treatment,Depth) %>%
  nest() 

head(Box4_nest)
```

# modeling nested data
 --> I will NOT be modeling data from box 4; this box was rudely eaten by some field animals, and there is not enough data to continue analysis. 
## box 3: Water Content
```{r}
Box3_WC_models <- Box3_nest %>%
  mutate(mods = map(data, ~ sens.slope(.x$WC))) #create new column 'mods' with the data (when you nest data by default R will call it 'data') by the function sens.slope, in the column conc inside the said bundled data (symbolized with the .x) 

head(Box3_WC_models)
Box3_WC_models$mods[3]

Box3_WC_Summaries <- Box3_WC_models %>%
  mutate(tidy_mods = map(mods, tidier)) %>%
  unnest(tidy_mods) %>%
  select(Treatment, Depth, p.value, slope) %>%
  mutate(trend = ifelse(p.value < 0.05, 'yes', 'no')) #new column for if there is a trend as an if_else
head(Box3_WC_Summaries)
```

## box 3: Temperature
```{r}
Box3_temp_models <- Box3_nest %>%
  mutate(mods = map(data, ~ sens.slope(.x$Temp))) #create new column 'mods' with the data (when you nest data by default R will call it 'data') by the function sens.slope, in the column conc inside the said bundled data (symbolized with the .x) 

head(Box3_temp_models)
Box3_temp_models$mods[3]

Box3_temp_Summaries <- Box3_temp_models %>%
  mutate(tidy_mods = map(mods, tidier)) %>%
  unnest(tidy_mods) %>%
  select(Treatment, Depth, p.value, slope) %>%
  mutate(trend = ifelse(p.value < 0.05, 'yes', 'no')) #new column for if there is a trend as an if_else
head(Box3_temp_Summaries) # this is good, we expect temperature to change over time!
```
